Traceback (most recent call last):
  File "/Users/farya/Documents/MachineLearning/Week6/image_capt_scratch/model.py", line 242, in <module>
    train_on_10_examples(
  File "/Users/farya/Documents/MachineLearning/Week6/image_capt_scratch/model.py", line 197, in train_on_10_examples
    encoder_output = encoder(image_tensors[i].unsqueeze(0))
  File "/Users/farya/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/farya/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/farya/Documents/MachineLearning/Week6/image_capt_scratch/model.py", line 72, in forward
    x = self.positional_encoding(x)
  File "/Users/farya/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/farya/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/farya/Documents/MachineLearning/Week6/image_capt_scratch/model.py", line 27, in forward
    x = x + self.pe[:, :x.size(1), :]
RuntimeError: The size of tensor a (784) must match the size of tensor b (49) at non-singleton dimension 1
Traceback (most recent call last):
  File "/Users/farya/Documents/MachineLearning/Week6/image_capt_scratch/model.py", line 242, in <module>
    train_on_10_examples(
  File "/Users/farya/Documents/MachineLearning/Week6/image_capt_scratch/model.py", line 197, in train_on_10_examples
    encoder_output = encoder(image_tensors[i].unsqueeze(0))
  File "/Users/farya/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/farya/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/farya/Documents/MachineLearning/Week6/image_capt_scratch/model.py", line 72, in forward
    x = self.positional_encoding(x)
  File "/Users/farya/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/Users/farya/Library/Python/3.9/lib/python/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/farya/Documents/MachineLearning/Week6/image_capt_scratch/model.py", line 27, in forward
    x = x + self.pe[:, :x.size(1), :]
RuntimeError: The size of tensor a (784) must match the size of tensor b (49) at non-singleton dimension 1
